# Generated by Django 2.2.3 on 2019-07-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='slug',
        ),
    ]
