# Generated by Django 2.2.3 on 2019-07-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_foods_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
