# Generated by Django 2.2.3 on 2019-07-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_foods_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foods',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foods',
            name='images',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
