# Generated by Django 2.2.3 on 2019-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20190710_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='check_field',
            field=models.BooleanField(default=True),
        ),
    ]
