# Generated by Django 2.2.3 on 2019-07-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_drinks_salads'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drinks',
            name='sell_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foods',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foods',
            name='sell_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salads',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salads',
            name='sell_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='check_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foods',
            name='check_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salads',
            name='check_field',
            field=models.BooleanField(default=False),
        ),
    ]
