# Generated by Django 2.2.3 on 2019-07-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_auto_20190713_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='check_field',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='sell_field',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='check_field',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='sell_field',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='check_field',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='sell_field',
        ),
    ]
