# Generated by Django 2.2.3 on 2019-07-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0009_auto_20190729_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodstypename', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersid', models.PositiveIntegerField(default=1)),
                ('count', models.PositiveIntegerField(default=1)),
                ('foodsid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foods.Foods')),
                ('foodstype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.FoodsType')),
            ],
        ),
    ]
