# Generated by Django 2.2.3 on 2019-07-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190715_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_foods',
            old_name='food_id',
            new_name='foods_id',
        ),
    ]
