# Generated by Django 2.2.3 on 2019-07-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_auto_20190719_2229'),
        ('users', '0003_auto_20190715_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods_type', models.PositiveIntegerField(default=1)),
                ('count', models.PositiveIntegerField(default=1)),
                ('foods_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foods.Foods')),
                ('users_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
        migrations.DeleteModel(
            name='Users_Foods',
        ),
    ]
