# Generated by Django 2.2.3 on 2019-07-29 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190719_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodstypename', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersfoods',
            name='foods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.FoodsType'),
        ),
    ]
