# Generated by Django 2.2.3 on 2019-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190729_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfoods',
            name='foods_type',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
