# Generated by Django 2.2.3 on 2019-07-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190729_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfoods',
            name='foods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.FoodsType'),
        ),
    ]
