# Generated by Django 2.2.3 on 2019-07-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190729_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersfoods',
            name='users_id',
        ),
    ]
